baseURL: http://example.org/
languageCode: en-us
title: Newbound AI
theme: agnes-hugo-theme
params:
  authorName: Ported to Hugo by Newman
  content:
    ButtonCaption: Pricing & Plans
    ButtonURL: http://google.com
    LeadDescription:  We specialize in leveraging AI technologies to streamline patent operations, reduce costs, and accelerate decision-making processes.
    LeadTitle: An AI Startup with cutting-edge AI solutions
  dateFormat: Jan 2, 2023
  feature:
    - FeatureDescription:  Utilizing Natural Language Processing (NLP) technology, this engine allows users to conduct precise patent searches through natural language queries, significantly enhancing the speed and accuracy of finding relevant patents.
      FeatureImage: images/feature-1.png
      FeatureTitle: Intelligent Patent Search Engine
    - FeatureDescription: This tool employs machine learning algorithms to automatically categorize and label patent documents, aiding users in swiftly filtering and identifying patents in relevant fields. It also offers in-depth data analysis, revealing industry trends and directions of technological development.
      FeatureImage: images/feature-2.png
      FeatureTitle: Patent Classification and Analysis Tool
    - FeatureDescription:  Integrates AI models and historical data analysis to evaluate the potential value and commercialization prospects of patents, providing data support for patent transactions and licensing decisions.
      FeatureImage: images/feature-3.png
      FeatureTitle: Patent Value Assessment System
    - FeatureDescription: Utilizing advanced predictive models to analyze trends in patent applications and grants, forecasting the future direction of technological development, helping patent companies grasp industry dynamics, and optimizing R&D and investment strategies.
      FeatureImage: images/feature-4.png
      FeatureTitle: Predictive Analysis Tool
  google_analytics_id: GA-
  pricing:
    - ButtonCaption: Get Early Access
      Features:
        - Description: Development of tailored AI tools and systems specific to patent companies needs.
        - Description: Focus on automation and intelligence in patent document processing and intelligent 
        - Description: recommendation systems.
      PricingRate: '27'
      PricingTitle: Customized AI Solutions
    - ButtonCaption: Get Earlier Access
      Features:
        - Description: Professional consulting services to help understand 
        - Description: and apply the latest AI technologies.
        - Description: Support for achieving automation and intelligence in patent management and operations.

      PricingRate: '97'
      PricingTitle: Technical Consulting
    - ButtonCaption: Get Earliest Access
      Features:
        - Description: Comprehensive big data services including processing
        - Description: cleaning, and analysis. 
        - Description: Aimed at extracting valuable insights from extensive patent datasets.
        
      PricingRate: '147'
      PricingTitle: Data Processing and Analysis
  social:
    FacebookURL: https://facebook.com/
    GoogleURL: http://google.com
    TwitterURL: https://twitter.com/
menu:
  main:
    - Name: Contact
      URL: '#'
      weight: 1
    - Name: About us
      URL: '#'
      weight: 2
    - Name: FAQ's
      URL: '#'
      weight: 3
    - Name: Support
      URL: '#'
      weight: 4
