baseURL: http://example.org/
languageCode: en-us
title: Agnes Site
theme: agnes-hugo-theme
params:
  authorName: Ported to Hugo by Debashish
  content:
    ButtonCaption: Pricing & Plans
    ButtonURL: http://google.com
    LeadDescription:  We specialize in leveraging AI technologies to streamline patent operations, reduce costs, and accelerate decision-making processes.
    LeadTitle: An AI Startup with cutting-edge AI solutions
  dateFormat: Jan 2, 2023
  feature:
    - FeatureDescription:  Utilizing Natural Language Processing (NLP) technology, this engine allows users to conduct precise patent searches through natural language queries, significantly enhancing the speed and accuracy of finding relevant patents.
      FeatureImage: images/feature-1.png
      FeatureTitle: Intelligent Patent Search Engine
    - FeatureDescription: This tool employs machine learning algorithms to automatically categorize and label patent documents, aiding users in swiftly filtering and identifying patents in relevant fields. It also offers in-depth data analysis, revealing industry trends and directions of technological development.
      FeatureImage: images/feature-2.png
      FeatureTitle: Patent Classification and Analysis Too
    - FeatureDescription:  Integrates AI models and historical data analysis to evaluate the potential value and commercialization prospects of patents, providing data support for patent transactions and licensing decisions.
      FeatureImage: images/feature-3.png
      FeatureTitle: Patent Value Assessment System
    - FeatureDescription: Utilizing advanced predictive models to analyze trends in patent applications and grants, forecasting the future direction of technological development, helping patent companies grasp industry dynamics, and optimizing R&D and investment strategies.
      FeatureImage: images/feature-4.png
      FeatureTitle: Predictive Analysis Tool
  google_analytics_id: GA-
  pricing:
    - ButtonCaption: Get Early Access
      Features:
        - Description: Lorem ipsum is common text
        - Description: Lorem ipsum is common text
        - Description: Lorem ipsum is common text
        - Description: Lorem ipsum is common text
      PricingRate: '27'
      PricingTitle: Starter
    - ButtonCaption: Get Earlier Access
      Features:
        - Description: Lorem ipsum is common text
        - Description: Lorem ipsum is common text
        - Description: Lorem ipsum is common text
        - Description: Lorem ipsum is common text
      PricingRate: '97'
      PricingTitle: Professional
    - ButtonCaption: Get Earliest Access
      Features:
        - Description: Lorem ipsum is common text
        - Description: Lorem ipsum is common text
        - Description: Lorem ipsum is common text
        - Description: Lorem ipsum is common text
      PricingRate: '147'
      PricingTitle: Business
  social:
    FacebookURL: https://facebook.com/podbharati
    GoogleURL: http://google.com
    TwitterURL: https://twitter.com/podbharati
menu:
  main:
    - Name: Contact
      URL: '#'
      weight: 1
    - Name: About us
      URL: '#'
      weight: 2
    - Name: FAQ's
      URL: '#'
      weight: 3
    - Name: Support
      URL: '#'
      weight: 4
